window.outdoorSpots = [
  {
    slug: "la-jolla",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "la-jolla.html",
    city: "San Diego",
    name: "Scripps Beach",
    pickerLabel: "La Jolla",
    pinLabel: "La Jolla",
    location: "La Jolla / Scripps Pier",
    lat: 32.873,
    lon: -117.253,
    hasModelForecast: true,
    cameraLabel: "Scripps Pier cam",
    cameraUrl: "https://coollab.ucsd.edu/pierviz/",
    image: "camera-snapshots/san-diego.png?v=20260618-0357",
    imageAlt: "Scripps Pier underwater visibility camera preview",
    imageLabel: "Daily camera frame",
    swellBounds: [
      [-117.345, 32.702],
      [-117.205, 32.908],
    ],
    tideStation: {
      id: "9410230",
      label: "NOAA La Jolla 9410230",
    },
    regionLabel: "La Jolla, San Diego",
    grade: null,
    gradeClass: "",
    primaryText: "La Jolla model",
    fill: 0,
    metrics: [
      ["Visibility", "Model forecast"],
      ["Water", "—"],
      ["Wind", "—"],
      ["Window", "—"],
    ],
  },
  {
    slug: "monterey",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "monterey.html",
    city: "Monterey",
    name: "Monterey",
    pickerLabel: "Monterey",
    pinLabel: "Monterey",
    location: "Monterey Bay",
    lat: 36.6011,
    lon: -121.8946,
    marineLat: 36.64,
    marineLon: -121.80,
    hasModelForecast: false,
    cameraLabel: "Live camera",
    cameraUrl: "https://www.portolahotel.com/our-hotel/webcam",
    liveEmbedUrl: "https://portal.hdontap.com/s/embed/?stream=portola_ttv-DMS&ratio=16:9",
    liveEmbedInPage: false,
    image: "https://portal.hdontap.com/snapshot/portola_ttv-DMS",
    imageAlt: "Monterey marina / Custom House Plaza live camera from Portola Hotel",
    imageLabel: "Live camera",
    swellBounds: [
      [-122.12, 36.50],
      [-121.58, 36.84],
    ],
    tideStation: {
      id: "9413450",
      label: "NOAA Monterey 9413450",
    },
    regionLabel: "Monterey Bay",
    grade: null,
    gradeClass: "",
    primaryText: "Vis grade unavailable",
    fill: 0,
    metrics: [
      ["Visibility", "Unavailable"],
      ["Water", "—"],
      ["Wind", "—"],
      ["Window", "—"],
    ],
  },
  {
    slug: "catalina-wrigley",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "catalina-wrigley.html",
    city: "Catalina Island",
    name: "Wrigley Reserve",
    pickerLabel: "Wrigley",
    pinLabel: "Catalina Wrigley",
    location: "Wrigley Reserve, Catalina Island",
    lat: 33.438,
    lon: -118.492,
    hasModelForecast: false,
    cameraLabel: "Live Catalina reserve cam",
    cameraUrl: "https://www.youtube.com/watch?v=JH_NzhSsqis",
    liveEmbedUrl: "https://www.youtube.com/embed/JH_NzhSsqis?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    image: "",
    imageAlt: "Catalina Wrigley reserve camera",
    imageLabel: "Live camera",
    swellBounds: [
      [-118.62, 33.32],
      [-118.32, 33.58],
    ],
    tideStation: {
      id: "9410079",
      label: "NOAA Avalon 9410079",
    },
    regionLabel: "Catalina Island",
    grade: null,
    gradeClass: "",
    primaryText: "Vis grade unavailable",
    fill: 0,
    metrics: [
      ["Visibility", "Unavailable"],
      ["Water", "—"],
      ["Wind", "—"],
      ["Window", "—"],
    ],
  },
  {
    slug: "anacapa-ocean",
    sport: "dive",
    sportLabel: "DIVE",
    regionGroup: "California",
    href: "anacapa-ocean.html",
    city: "Channel Islands",
    name: "Anacapa Ocean",
    pickerLabel: "Anacapa",
    pinLabel: "Anacapa",
    location: "Anacapa Ocean, Channel Islands",
    lat: 34.010,
    lon: -119.366,
    hasModelForecast: false,
    cameraLabel: "Live Anacapa cam",
    cameraUrl: "https://www.youtube.com/watch?v=OAJF1Ie1m_Q",
    liveEmbedUrl: "https://www.youtube.com/embed/OAJF1Ie1m_Q?autoplay=1&mute=1&playsinline=1&controls=1&rel=0&modestbranding=1",
    image: "",
    imageAlt: "Anacapa Ocean camera",
    imageLabel: "Live camera",
    swellBounds: [
      [-119.52, 33.92],
      [-119.22, 34.12],
    ],
    tideStation: {
      id: "9411340",
      label: "NOAA Santa Barbara 9411340",
      fallbackId: "9410840",
      fallbackLabel: "NOAA Santa Monica 9410840",
    },
    regionLabel: "Channel Islands",
    grade: null,
    gradeClass: "",
    primaryText: "Vis grade unavailable",
    fill: 0,
    metrics: [
      ["Visibility", "Unavailable"],
      ["Water", "—"],
      ["Wind", "—"],
      ["Window", "—"],
    ],
  },
];

window.californiaSpots = function californiaSpots() {
  return (window.outdoorSpots || []).filter((spot) => spot.regionGroup === "California");
};

window.spotFromSlug = function spotFromSlug(slug) {
  const spots = window.californiaSpots();
  return spots.find((spot) => spot.slug === slug) || spots[0] || null;
};
